package album

import(
	"testing"
	"github.com/stretchr/testify/assert"
    "net/http/httptest"
	"fmt"
	"github.com/gin-gonic/gin"
	"encoding/json"
	
)

type AutoGenerated struct {
	ID     string  `json:"id"`
	Title  string  `json:"title"`
	Artist string  `json:"artist"`
	Price  float64 `json:"price"`
}

var mockAlbums = []AutoGenerated {
    {ID: "1", Title: "Blue Train", Artist: "John Coltrane", Price: 56.99},
    {ID: "2", Title: "Jeru", Artist: "Gerry Mulligan", Price: 17.99},
    {ID: "3", Title: "Sarah Vaughan and Clifford Brown", Artist: "Sarah Vaughan", Price: 39.99},
}


func TestGetAlbums(t *testing.T)  {
	w := httptest.NewRecorder()
    c, _ := gin.CreateTestContext(w)
    GetAlbums(c)
	fmt.Println("getAlbumBy w", w, w.Body)
    assert.Equal(t, 200, w.Code)

    var got []gin.H
    err := json.Unmarshal(w.Body.Bytes(), &got)
	fmt.Println("getAlbumBy err", err)
    if err != nil {
        t.Fatal(err)
    }
    assert.Equal(t, mockAlbums, got) // want is a gin.H that contains the wanted map.
}

